import streamlit as st
import pandas as pd
import joblib
import numpy as np

# ================= Configuration =================
st.set_page_config(
    page_title="脑卒中后患相关肺炎（SAP）风险预测",
    page_icon="🏥",
    layout="centered"
)

# Custom CSS for medical-grade styling
st.markdown("""
    <style>
    .main {background-color: #f8f9fa;}
    .stButton>button {
        width: 100%;
        background-color: #007bff;
        color: white;
        font-size: 18px;
        font-weight: bold;
        padding: 12px;
        border-radius: 8px;
        border: none;
        transition: 0.3s;
    }
    .stButton>button:hover {
        background-color: #0056b3;
    }
    .result-card {
        padding: 25px;
        border-radius: 12px;
        box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        text-align: center;
        margin-top: 25px;
        font-family: 'Arial', sans-serif;
    }
    .input-label {
        font-weight: 600;
        font-size: 14px;
    }
    </style>
""", unsafe_allow_html=True)

# ================= Header =================
st.title("🏥 脑卒中相关肺炎（SAP）风险预测")
st.markdown("""
    本工具基于优化的 **Logistic Regression** 机器学习模型。通过整合核心的临床评分与实验室检验指标，为您提供急性脑卒中患者并发 **SAP** 的实时发病风险评估。
""")
st.markdown("---")

# ================= Load Model =================
@st.cache_resource
def load_model_data():
    try:
        # Load the file generated by your training script
        return joblib.load('web_app_data.pkl')
    except FileNotFoundError:
        return None

data = load_model_data()

if data is None:
    st.error("⚠️ 未找到模型文件 ('web_app_data.pkl')。请先运行训练脚本生成该文件。")
    st.stop()

model = data['model']

# 严格按照最新稳定性 LASSO 筛选出的 4 个特征顺序
required_features = ['NIHSS', 'PTr', 'age', 'neutrophil']

# ================= Input Form =================
with st.form("prediction_form"):
    
    # --- Section 1: Demographics & Clinical Scores ---
    st.subheader("👤 基本情况与临床评分")
    col1, col2 = st.columns(2)

    with col1:
        age = st.number_input("年龄 (Age, years)", min_value=18, max_value=120, value=65, step=1)

    with col2:
        # NIHSS scale typically ranges from 0 to 42
        nihss = st.number_input("NIHSS评分 (Stroke Scale)", min_value=0, max_value=42, value=4, step=1)

    st.markdown("<br>", unsafe_allow_html=True)  # Spacing

    # --- Section 2: Blood & Coagulation Markers ---
    st.subheader("🩸 实验室检验指标")
    col3, col4 = st.columns(2)

    with col3:
        # Prothrombin Time Ratio
        ptr = st.number_input("凝血酶原时间比值 (PTr)", min_value=0.50, max_value=5.00, value=1.00, format="%.2f")

    with col4:
        # Neutrophil Count
        neutrophil = st.number_input("中性粒细胞计数 (Neutrophil, 10⁹/L)", min_value=0.00, max_value=50.00, value=4.00, format="%.2f")

    st.markdown("<br>", unsafe_allow_html=True)  # Spacing
    
    # ================= Prediction Submit =================
    submitted = st.form_submit_button("🚀 计算感染风险 (Calculate Risk)")

if submitted:
    # 1. Collect inputs into a dictionary
    # 键名必须与模型训练时的原始特征列名绝对一致
    input_data = {
        'NIHSS': nihss,
        'PTr': ptr,
        'age': age,
        'neutrophil': neutrophil
    }

    # 2. Convert to DataFrame (ensures correct column names)
    input_df = pd.DataFrame([input_data])

    # 3. Ensure column order matches the trained model exactly
    try:
        input_df = input_df[required_features]
    except KeyError as e:
        st.error(f"系统错误：模型需要特征 {e}，但未提供。")
        st.stop()

    # 4. Make Prediction
    try:
        # Predict Probability (index 1 is the positive class 'SAP')
        probability = model.predict_proba(input_df)[0][1]

        # Determine Risk Level
        risk_percentage = probability * 100

        st.markdown("---")

        # Display Result Card
        if probability >= 0.5:
            st.markdown(f"""
                <div class="result-card" style="background-color: #ffebee; border: 2px solid #ef5350;">
                    <h2 style="color: #c62828;">⚠️ 高风险 (High Risk)</h2>
                    <h1 style="font-size: 50px; color: #c62828; margin: 10px 0;">{risk_percentage:.1f}%</h1>
                    <p style="font-size: 18px; color: #b71c1c;">
                        结果提示该患者发生卒中相关性肺炎（SAP）的风险较<b>高</b>。<br>建议加强气道管理与临床监测。
                    </p>
                </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown(f"""
                <div class="result-card" style="background-color: #e8f5e9; border: 2px solid #66bb6a;">
                    <h2 style="color: #2e7d32;">✅ 低风险 (Low Risk)</h2>
                    <h1 style="font-size: 50px; color: #2e7d32; margin: 10px 0;">{risk_percentage:.1f}%</h1>
                    <p style="font-size: 18px; color: #1b5e20;">
                        结果提示该患者发生卒中相关性肺炎（SAP）的风险较<b>低</b>。<br>按常规护理流程进行观察即可。
                    </p>
                </div>
            """, unsafe_allow_html=True)

        # 5. Interpretation / Visual Guide
        st.write("")
        st.write("### 📉 风险概率可视化")
        st.progress(int(risk_percentage))
        st.caption("0% = 无风险 | 50% = 临床预警阈值 | 100% = 极高风险")

    except Exception as e:
        st.error(f"预测过程中发生错误: {str(e)}")